image: alpine
before_script:
  - apk update && apk add git openssh
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod -R 0600 ~/.ssh
  - echo $(ssh-agent -s)
  - yes | ssh-add ~/.ssh/id_rsa

mirror:
  script:
    - git remote add github git@github.com:tclarke/test.git || true
    - git push --all github
  tags:
    - docker
