image: alpine
before_script:
  - apk update && apk add git
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - printf "Host *\n  IdentityFile ~/.ssh/id_rsa\n" > ~/.ssh/config
  - chmod -R 0600 ~/.ssh

mirror:
  script:
    - git remote add github git@github.com:tclarke/test.git || true
    - git push --all github
  tags:
    - docker
