image: alpine
before_script:
  - apk update && apk add git openssh
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod -R 0600 ~/.ssh
  - eval $(ssh-agent -s)
  - yes | ssh-add ~/.ssh/id_rsa || true
  - git remote | grep github && git remote remove github
  - ssh-keygen -R github.com || true
  - ssh-keyscan github.com >> ~/.ssh/known_hosts || true

mirror:
  script:
    - git remote add github git@github.com:tclarke/test.git
    - git push --all github
  tags:
    - docker
