image: alpine
before_script:
  - apk update && apk add git openssh
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

mirror:
  script:
    - git remote add github git@github.com:tclarke/test.git
    - git push --all github
